# Generated by Django 5.0.7 on 2024-08-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Price', models.IntegerField()),
                ('category', models.CharField(choices=[('veg', 'veg'), ('non', 'non veg')], max_length=20)),
            ],
        ),
    ]
